### ISSUE TITLE
Experience for Kerbals is incorrect in current version

### ISSUE THREAD

**Issue by dringdahl** [Kopernicus/Kopernicus#154]
After updating Kopernicus to v1.2.2-2, I only receive 2xp each for orbit of the Mun and Minmus for my Kerbals. If I revert Kopernicus to v1.2.1-3, the xp is correct. I am using KSP v1.2.2 and I have a rather long mod list. Please let me know what information you would like to help you discover the source of the problem.

**Comment by Sigma88** [comment]
remove all other mods, repeat the test, if the problem still exist then we can look at it.

I expect the issue to disappear, what's most likely is that you have installed a planet pack (or another mod) that changes the science multipliers
(OPM for example changes those)

reverting to kopernicus v1.2.1-3 on KSP 1.2.2 would disable kopernicus so that's not a solution, unless you are also using KSP 1.2.1

**Comment by dringdahl** [comment]
You are correct. It was OPM.
