### ISSUE TITLE
clock feature issues

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#159]
I've received this report from OhioBob but I haven't had time to look into it

---------------------------------------------------------------

I've tried implementing this feature but haven't been able to get it to work.  I'm using Sigma Dimensions to produce different sized versions of GPP.  Below is the Sigma config for the 6.4x version (at least as is stand now, there may be additional adjustments later).  As you can see, I adjusted the home world's day by 2.5x, making it 15 hours long.

```
@SigmaDimensions
{
	// Base Settings

	@Resize = 6.4
	@Rescale = 6.4
	@Atmosphere = 1.2
	@dayLengthMultiplier = 1


	// Advanced Settings

	@landscape = 0.57
	@geeASLmultiplier = 1

	@resizeScatter = 1
	@resizeBuildings = 0

	@CustomSoISize = 0
	@CustomRingSize = 0

	@atmoASL = 1
	@tempASL = 1
	@atmoTopLayer = 1.333333333
	@atmoVisualEffect = 1.2

	@scanAltitude = 1
}

@Kopernicus:BEFORE[SigDim2]:NEEDS[SigDim]
{
	@Body:HAS[#name[Kerbin]]
	{
		@SigmaDimensions
		{
			@dayLengthMultiplier = 2.5
		}
	}
}
```

Everything above appears to be working just fine.  To use the Kopernicus modified clock, I made a separate config containing the following code and placed in inside the GPP folder.  Unfortunately it's not working; the days are still turning over after 6 hours.  There is probably something simply that I'm messing up.  Any suggestions?

```
@Kopernicus
{
    useKopernicusTime = true
} 
```

@ohiobob if you have some log files it might help @thomas 

I'm not sure if I can manage to take a look at it myself, I'm slightly too busy in this period :/

**Comment by StollD** [comment]
I think this is a mess-up by me (and a bit @Sigma88 but mainly me, because I should've corrected his pull request :P)

Basically, we store the stock time settings in theese variables https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus/Kopernicus/RuntimeUtility/ClockFixer.cs#L89-L93

By default, all those values are 0, because that is how C# works. The stock values are assigned here: https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus/Kopernicus/Configuration/ClockLoader.cs

The problem now is, that both of us, Sigma and me, missed that the code in ClockLoader.cs will never get executed if you dont have a KopernicusTime { } node inside of your Kopernicus { } node. @OhioBob please try to add this node (it can be completely empty) to your config. If I am not misstaken, everything should work then.

**Comment by OhioBob** [comment]
@StollD, yes, that did the trick.  It's working now.  All I did was change to my config to the following.  Thank you very much for the help.

`@Kopernicus
{
	useKopernicusTime = true
	KopernicusTime{} 
}`

**Comment by Sigma88** [comment]
actually I always intended for it to work without the node,

if @StollD you haven't changed anything it means it's a mess up by me

but it's weird because I thought I did make sure it was working without the node...

I can't remember now to be honest, and I think requiring both the bool and the node is a bit pointless, we can maybe change it on a future release so that it doesn't require the node.

**Comment by StollD** [comment]
@Sigma88 Remember who was the one that sent you a pastebin with improvements? :D 

I would say this is my fault

**Comment by Sigma88** [comment]
ah yes

this is the problem

https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus/Kopernicus/RuntimeUtility/ClockFixer.cs#L43-L50

if those numbers are 0 then the if will fail
