### ISSUE TITLE
Kopernicus stops solar panels from deploying

### ISSUE THREAD

**Issue by Noor-747** [Kopernicus/Kopernicus#192]
It retracts solar panels and stops them producing power if they are mounted flat, I have read a few other people reporting this on other sites, please look into it, not just for me but in general for everyone.

**Comment by Sigma88** [comment]
I'm assuming you tested this with just Kopernicus to make sure it's a kopernicus issue since you didn't mention any other mods.

I'm also not seeing the issue, [here's](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-130-122-kopernicus-release-4-june-15/&page=27#comment-2793409) a list of files we need from you to see what's going bad on your game

**Comment by Noor-747** [comment]
I've deleted it and then reinstalled, the issue seems to have disappeared,
thank you anyway although im certain it was originally caused by this mod.

**Comment by Sigma88** [comment]
glad you managed to solve your issue
