### ISSUE TITLE
Switch from LGPL to MIT

### ISSUE THREAD

**Issue by StollD** [Kopernicus/Kopernicus#209]
For some time I've been thinking about switching Kopernicus to the MIT license (as opposed to the LGPL), and I finally took the time to write this proposal. My reasons for it are fairly simple:

* MIT is way **easier** than the LGPL (7600 characters vs. 1050 characters)
* MIT is more **open** than LGPL (it allows other people to do whatever they want with the code, they only need to give proper credit)
* Because of that it is also more **compatible** with other licenses.
* And my personal experience has shown that the MIT license is way better than the LGPL
* Kopernicus is not just a planet adding mod anymore. It is full of Utility functions and libraries, and I have often used them in other mods with different licenses. MIT would make using single functions or libraries from Kopernicus easier.

Thats why I am asking everyone who contributed to Kopernicus if they are ok with me relicensing the code and future releases under the MIT License.

- [ ] @Teknoman117 
- [ ] @NathanKell 
- [x] @Sigma88 
- [ ] @Gravitasi 
I would call those the major contributors (please correct me if you see this differently)
---------------- 
- [ ] @BryceSchroeder 
- [x] @Gerry1135 
- [ ] @HappyFaceIndustries 
- [x] @HebaruSan 
- [x] @LGhassen 
- [ ] @Starstrider42 
- [ ] @Josh6680 
- [ ] @dpentz 
- [ ] @WazWaz 
- [x] @Olympic1 
- [x] @dbent 
---------------- 
- [ ] @KillAshley (for KopernicusExamples)

The license change would affect the [Kopernicus](https://github.com/Kopernicus/Kopernicus), [KopernicusExamples](https://github.com/Kopernicus/KopernicusExamples) and [config-parser](https://github.com/Kopernicus/config-parser) repositories.

**Comment by dbent** [comment]
I agree. 👍

**Comment by BryceSchroeder** [comment]
I respectfully disagree.

 The MIT license does not protect the project from being modified by
someone and put under some proprietary license, or requiring it to be
bundled with spyware, or some other monstrous thing. It's been a long time
since I've been regularly involved with this project (there are probably
devs who don't know that I actually started it back in 2014) but for what
it's worth, I am not okay with anyone releasing anything I did under a
license apart from the LGPL, and strongly discourage others from consenting
to this.

I am okay with licensing it to other mod develops on a case-by-case basis
for use with code that has to have a license that presents difficulty for
the LGPL, if they aren't doing anything malign with it.

Maybe we could clarify that people using the API functions Kopernicus
provides do not have to be GPL/LGPL licensed, sort of like the Linux Kernel
APIs? I at least have no problem with that.

**Comment by HebaruSan** [comment]
Just in case this is still a live question after Bryce's response, I consent to having my (minor) contributions published under LGPL, MIT, GPL, or public domain.

**Comment by Gerry1135** [comment]
I suspect you're right about this now being a dead issue but, for the record, while I don't fully agree with all the reasons StollD gave, I would agree to my contributions being relicensed under the MIT license (as all my personal KSP mod projects are).

**Comment by LGhassen** [comment]
I'm okay with MIT license.

**Comment by Olympic1** [comment]
I agree

**Comment by Teknoman117** [comment]
For some reason this showed up in my notifications today.

I'm generally of the same mindset at @BryceSchroeder .

However, one thing that could be done is move as much of the Kopernicus utility logic into a separate Kopernicus utility DLL.  LGPL doesn't prevent you from using the library from some other project (open or proprietary), just that you must be able to swap the library for a different version, a derivative version, or something else entirely.  Compartmentalizing the functionality that makes sense to export would make it easier to use with other projects.
