### ISSUE TITLE
Give user feedback during initial cache generation

### ISSUE THREAD

**Issue by HebaruSan** [Kopernicus/Kopernicus#268]
## Problem

New users installing planet packs frequently report that their game is freezing up during load, when in fact it's working fine, Kopernicus just needs to generate its cache.

## Suggestion

Print something to the screen during this process so it doesn't look like the game has frozen. Something in the progress bar area would be ideal, but even a simple "Generating Kopernicus cache..." popup would be sufficient.

**Comment by StollD** [comment]
The problem is that the whole Kopernicus loading process (including the cache generation) happens in one single frame. Since the loading logic is executed before any UI logic, the notice wouldn't show up until the next frame (which already starts loading the main menu). Displaying the message in the last frame before Kopernicus starts its work would work, but thats probably pretty annoying.

The real solution for this issue is, that planet makers ship pregenerated .bin files (i.e. the exported ScaledSpace cache files) with their mods, so Kopernicus doesn't have to generate them on the PC's of the end-user.

**Comment by HebaruSan** [comment]
Is there anything to tell planet pack authors that they should do that? I took a look at the Kopernicus wiki, and these links are both broken:

![image](https://user-images.githubusercontent.com/1559108/36223650-fdf5e708-11bc-11e8-891e-4ee2e04fedbc.png)

... and the rest is config file syntax documentation. "How to package and release a planet pack" would be a nice page to have if there are specific expectations regarding that.

**Comment by Sigma88** [comment]
@HebaruSan some mods will trigger the re-generation of cache files so even that would not be a complete solution

the only real solution that works 100% of the times is having patience
