### ISSUE TITLE
Parts exploding due to overheating

### ISSUE THREAD

**Issue by seanth** [Kopernicus/Kopernicus#297]
Craft parts explode when used with Kopernicus. Sometimes the heat explosions happen when zooming out in map view. Other times parts explode due to heat when changing where the craft is controlled from.

Logs at https://www.dropbox.com/sh/qn25y5bnkgs63xq/AADI1G_i8iNa0jD2MAiBdfwZa?dl=0

Video showing an example at https://youtu.be/VRLnmuM9F5o?t=1m24s

I will cross post a this bug with the ResearchBodies repo as well since I am mainly seeing the explosions in relation to telescopes. Logs make me think it has something to do with sunlight switching, though.

**Comment by Bazsy** [comment]
Happened to me two times a few days ago. (I use 1.4.3). Im not sure if it's because of Kopernicus or something else. Never had the issue before 1.4.4 came out.
One happened when I left the Muns SoI and another one during a landing with a booster (it came in pretty hard and wasn't going to make it but then it exploded in 7000m height. Long below the level where the heat is maximal and also the speed was something like a few hundred m/s.

**Comment by JarredEagley** [comment]
This sounds very similar to an issue I was getting with To Boldly Go. Couldn't figure out if it was a Kopernicus problem or a TBG problem, but it seems to be that when kopernicus switches light sources to a hotter star/object it causes your ship to overheat and explode. At one point it even listed some parts' temps as infinity!

**Comment by JarredEagley** [comment]
https://www.mediafire.com/file/8w7abk8ajiw68vs/Logs-Kopernicus.zip/file
Logs from my experience with this bug

**Comment by Sigma88** [comment]
this issue should have been solved but I always forgot to notify you guys,

could you please confirm that the bug is no longer there and that we can close this issue?

**Comment by Bazsy** [comment]
> this issue should have been solved but I always forgot to notify you guys,
> 
> could you please confirm that the bug is no longer there and that we can close this issue?

Yes, this is gone.

**Comment by Sigma88** [comment]
thanks for confirming this
