### ISSUE TITLE
Kerbals can't walk on surface

### ISSUE THREAD

**Issue by syscryp** [Kopernicus/Kopernicus#305]
Hi. I'm using Kopernicus and Sigma Dimensions so I can run Realistic Rescale 1.1.1. Unfortunately, my Kerbals can't walk on the surface of Kerbin while Kopernicus is on. The walking animation plays, but they don't move (except for a tiny little jitter forwards when you release W). They can run fine if you hold Shift - they just can't walk.

Uninstalling Kopernicus meant the problem went away immediately and Kerbals could walk again. Of course, that also means RR doesn't work...

Can you help?

**Comment by Sigma88** [comment]
have you tried contacting the devs of Realistic Rescale?

if you are the only one experiencing this issue it might be related with your setup rather than Kopernicus/SD/RR

more information would help look into the issue, I've tried SD on bigger planets and they always work fine as long as you don't go too far (like 100x)
