### ISSUE TITLE
Breaking Ground DLC (KSP 1.7.1)

### ISSUE THREAD

**Issue by DJDC13** [Kopernicus/Kopernicus#358]
After downloading and installing the new breaking ground dlc, Kopernicus (and therefore RSS) does not load. All the configs for Kopernicus RSS load and the sun still remains changed to the RSS size and brightness but none of the planets load.

**Comment by Gameslinx** [comment]
Kopernicus is version locked to 1.7 at the moment, since 1.7.1 is not yet supported. Please wait.

**Comment by Liwohka** [comment]
This creates another problem too. Because now I gotta run KSP without Kopernicus, which I earlier had while playin my career, ALL my satellites, probes, etc. are now solar panels closed. Also if for example action button "custom 1" is signed to "toggle panels" etc.->all these action buttons does not now work. So my savefiles have gone totally mad, satellites are literally dropping from sky (out of power), if i dont manually go trough every 200 pieces of equipment in space and open their panels. Also while opening old craft files, KSP says "missing component, kopernicus solarpanels". So every solarpanel that I have used or installed while playin with kopernicus is now out of order. Not nice. So hurry up.

**Comment by Gameslinx** [comment]
You are told when Kopernicus fails to load. Listen to the warning. When Kopernicus is released, load an autosave

TMSP develops Kopernicus for free and he can take as much time as he wants. He owes you nothing at all, so stop being a minge about it and wait.

**Comment by Sigma88** [comment]
> So hurry up.
wow, not nice
