### ISSUE TITLE
Broken Solar Panels

### ISSUE THREAD

**Issue by arperry99** [Kopernicus/Kopernicus#366]
Noticed that my solar panels stopped producing any charge despite them pointing correctly towards the sun. Right clicking on the panels shows that all the numbers are zero.

KSP.log shows this, so I figured I'd ask here:

> [EXC 11:21:31.215] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusSolarPanel.PostCalculateTracking (Boolean trackingLOS, Vector3 trackingDirection)
	ModuleDeployablePart.CalculateTracking ()
	ModuleDeployablePart.updateFSM ()
	ModuleDeployablePart.FixedUpdate ()
	ModuleDeployableSolarPanel.FixedUpdate ()

My guess is that the new system for multiple suns would be breaking something else in my game. I use Sigma Dimensions to rescale my game. 

LOGS:
[LogsForBrokenPanels.zip](https://github.com/Kopernicus/Kopernicus/files/3363499/LogsForBrokenPanels.zip)

**Comment by arperry99** [comment]
I also notice #364 Sigma has up. Maybe this could already be the fix?

**Comment by StiKsaS** [comment]
Any updates or a quick workaround?

**Comment by Galileo88** [comment]
@StiKsaS you can start a new game. The reason your solar panels broke is likely because you added Kopernicus after you had already started a game without it.
 
OR

If the planet pack or visual pack you added doesn’t add any new stars, you can remove the solar panel cfg that comes with Kopernicus and the panel behavior will return to stock, but you may have to adjust the panels and re-extend them if necessary.

This has been documented quite a bit in the Kopernicus thread. It’s a shame important info like this keeps getting buried by people asking for updates and arguing.  ¯\_(ツ)_/¯

**Comment by Sigma88** [comment]
I think my proposed change will reduce the amount of incompatibilities

I can't speak for thomas but it seemed to me he want opposed to the change

**Comment by arperry99** [comment]
Yeah I must have done something weird when I updated my game, I'll try yeeting that cfg when I get back from work.

I was hesitant to file an issue, but I decided to since I couldn't find a error like the one in my log. I have nothing but love for you guys taking care of this mod, sorry for all the BS you gotta deal with (for so long too.. lol).

**Comment by arperry99** [comment]
Getting rid of the solar panel cfg did the trick. Ill try a new game too, but this is enough for me to close the issue. Thanks!
