### ISSUE TITLE
Lag when entering map mode

### ISSUE THREAD

**Issue by DrGonzo94** [Kopernicus/Kopernicus#382]
Hi, thanks a million for a great mod!

With the new version of Kopernicus (1.7.3-2) I get a significant lag when entering map view. There is no lag when returning to spaceship view. The issue disappeared when I rolled back to 1.7.3-1.

**Comment by scott4dges** [comment]
Also seeing this issue running KSP 1.7.3 and the 1.7.3-2 build of Kopernicus with OPM and AVP/EVE. Freezing is consistently about 4.5 secs (after timing different craft in different SOI) regardless of craft part size or number of flights in progress, etc.

**Comment by DeltaDizzy** [comment]
Pre-1.5.1-1, loading biome maps into OnDemand caused lag in the Map View, so they were made to not load by default with 1.5.1-1. Between 1.7.3-1 and 1.7.3-2, they were once again made to load by default, presumably because it was believed the lag would not reoccur. (That last part is personal speculation and may or may not be true.) Can you try this patch and see if it fixes the lag?
```
@Kopernicus:FINAL
{
    %useOnDemandBiomes = false
}
```

**Comment by scott4dges** [comment]
Thank you for your super-fast response. I'll try that now and report back!

**Comment by scott4dges** [comment]
> Pre-1.5.1-1, loading biome maps into OnDemand caused lag in the Map View, so they were made to not load by default with 1.5.1-1. Between 1.7.3-1 and 1.7.3-2, they were once again made to load by default, presumably because it was believed the lag would not reoccur. (That last part is personal speculation and may or may not be true.) Can you try this patch and see if it fixes the lag?
> 
> ```
> @Kopernicus:FINAL
> {
>     %useOnDemandBiomes = false
> }
> ```

**Comment by scott4dges** [comment]
Thank you for your super-fast response. I'll try that now and report back!

**Comment by scott4dges** [comment]
Eureka! That definitely did the trick. No more lag when switching scenes between Flight and Map view.
Do you want me to post back to the KSP Forum thread? or maybe you'll make mention of this fix?

**Comment by DeltaDizzy** [comment]
I'm glad it worked on the first try! As for the forums, I don't really care, as long as people affected have the interim while the developers fix it for real.

**Comment by tomasbrod** [comment]
I spent about hour and a half bisecting my mod folder to find the source of lag, arrived at Kopernicus 1.7.3-1 -> 1.7.3-2 and then found the regression already reported.

**Comment by Galileo88** [comment]
Yup. This is not an issue with kopernicus. Mod authors need to update their work.

**Comment by Poodmund** [comment]
Low info .dds textures didn't seem to remove the issue either with biome OnDemand enabled so Thomas has reverted the change made in the last release so that biome texture are loaded and cached by default in a possible future release of Kopernicus.

I guess in the mean time, the band aid config fix is required to disable this feature as stated above if you want to remove the few seconds of delay when entering map mode but in time, if/when a new version of Kopernicus is released, this issue will "self-fix" itself.

Related commit: https://github.com/Kopernicus/Kopernicus/commit/449bad8920c0ff5f523354ddb34ca5bc949e5bd9

**Comment by Sigma88** [comment]
is this issue still happening? or can it be closed?
