### ISSUE TITLE
[Suggestion] Ability to disable version lock

### ISSUE THREAD

**Issue by Monniasza** [Kopernicus/Kopernicus#383]
The version lock setting will look like:

[] Kopernicus version lock

Useful if Kopernicus is not updated to newest version.

**Comment by StollD** [comment]
Sure. As long as you volunteer to take over support for every KSP version that the unlocked version runs on, even if it doesn't work correctly or at all. Which is, well, *every* version.

But since most people who want the version lock removed don't actually think about why it exists in the first place, and don't consider the implications of removing it, I am going to assume you are not going to do that.

And because I definitly won't support *every* KSP version (except the latest one + the ones that have backports) either, the version lock won't be removed, and I will close this issue.
