### ISSUE TITLE
Incompatible licensed work included in releases

### ISSUE THREAD

**Issue by R-T-B** [Kopernicus/Kopernicus#390]
This is unlikely to be popular, but I'm pointing it out for your own good (yes, it's me again.  Such a helpful presence I know).

You are including MFI (ModularFlightIntegrator) binary builds in your product.  They are subject to GPLv3 copyleft as explained [here](https://softwareengineering.stackexchange.com/questions/204410/how-are-gpl-compatible-licenses-like-mit-usable-in-gpl-programs-without-being-su).  You must submit them as GPLv3 if you are distributing your project as GPLv3.  That being said, you cannot simply resubmit them with your work as GPLv3, unless you have permission from the authors to re-release them under GPLv3 this is legally an issue.

This could open you up to a number of problems for actors with ill intent.  I would suggest a license change, or simply contact the original authors to ensure you have a leg to stand on.  Really changing to a compatible license is probably best, as DMCA requests defer to the side of caution and don't wait to kill projects.

Don't shoot the messenger, I'm trying to inform all projects with this issue, that is all.  (L)GPLv3 licenses are all an issue when used in distribution like this.  I would suggest MIT since you are linking to something with it, anyways.

Kopernicus rocks.  I'm writing this because a world without it would be majorly bad.

**Comment by R-T-B** [comment]
I've done further reading.  MIT may be ok since it is listed as "GPL compatible".  If someone could weigh  in that'd be great.  I'd still be cautious.

**Comment by StollD** [comment]
You simply get a multi-licensed zip file. 




Also, I am not exactly sure about this, but if they get bundled, the license of the *binary* changes. This requires the source code to be available (which is the case). The source code however is still subject to the MIT license.




I don't think it is that much different from KSP shipping MIT / LGPL licensed libraries: They don't suddenly become proprietary, you simply have a zip file where multiple files have different licenses.




Or for example mono: Back in the days, mono's core was licensed as LGPL and the C# libraries included with it were licensed under MIT. All of that was shipped in one gargantuan .exe file for Windows users. This is basically what's being done here.




sarbian knows about this, and Kopernicus is not the only mod doing this. MFI is a utility mod that is designed to be shipped by the mods depending on it.




Regarding changing the license: Even if I wanted to I couldn't do it. There are so many contributors, some of which are not active at all anymore and some object to changing the license.




Ultimately this is just a mod for a game, not a large company ignoring the terms of the GPL (Bukkit, since I've seen you bringing this up on the forum). I appreciate your effort, though, thank you. 




On Mon, Oct 21, 2019 at 8:04 AM +0200, "Raymond Beehler" <notifications@github.com> wrote:












I've done further reading.  MIT may be ok since it is listed as "GPL compatible".  If someone could weigh  in that'd be great.  I'd still be cautious.

**Comment by R-T-B** [comment]
I appreciate the feedback.  Further reading has me believe you are correct.  You aren't the only project I reported an issue in this fashion you may not, so I'm not singling you out.

Just trying to avoid a minefield.  I've seen bad things happen and wouldn't want them to happen to you.  If you think you've got a handle on this then thanks for reading, and closing.
