### ISSUE TITLE
Main Menu Screen Issue

### ISSUE THREAD

**Issue by WC12366** [Kopernicus/Kopernicus#426]
There are 2 main menu screens in KSP. The first one is 4 kerbals orbiting Kerbin, and the second one is 2 kerbals landed on the Mun. But after I install Kopernicus, the second screen disappeared

Steps to reproduce:
Open KSP without Kopernicus.
Click "Settings".
Go back to main menu.
The game will load the second screen.
Exit KSP.
Install Kopernicus and start the game.
Click "Settings"
Go back to main menu.
The game won't load the second screen.

**Comment by Sigma88** [comment]
>There are 2 main menu screens in KSP.
Internally, they are called "MunScene" and "OrbitScene"

Kopernicus turns off the MunScene because there is no guarantee that the scene would make sense in a system that has been modified by kopernicus.

I have a mod called [SigmaReplacements: MenuScenes](https://github.com/Sigma88/Sigma-Replacements/wiki) for customizing the MunScene that will allow to get both scenes showing even when using kopernicus, but admittedly there is no documentation and the syntax is not too easy.

However, if you have something specific in mind feel free to hit me up on discord and I can assist you in writing the necessary cfgs.

**Comment by WC12366** [comment]
Great mod! Thanks!

**Comment by WC12366** [comment]
Can you give me an example config?

**Comment by Sigma88** [comment]
if you just want to enable the stock scene this is all you need:

```
@SigmaReplacements
{
    MunScene
    {
        name = MunScene
        enabled = True
    }
}
```

this will only enable the stock scene, which might be broken depending on what system you are loading

**Comment by Sigma88** [comment]
the mod itself has a ton of features, and I am working on an update which will change the syntax slightly to add more features for 1.8.1/1.9.1

if you are interested in customizing your MunScene further, contact me on discord because this will require a more interactive discussion than just a couple of messages here.

I'm closing this issue for now since this seems resolved

**Comment by WC12366** [comment]
Thanks!

**Comment by Sigma88** [comment]
if you don't have discord, just open an issue on my mod's repo and I will try to help you as much as I can
