### ISSUE TITLE
No comets with Kopernicus

### ISSUE THREAD

**Issue by Folkoer** [Kopernicus/Kopernicus#503]
I read somewhere Kopernicus doesn't have comets and I just noticed their absence.
Will they ever be re-introduced?

**Comment by R-T-B** [comment]
We do technically support comets, but only in stock-like systems due to our reliance on the stock game generator.

You can make them spawn by setting useKopernicusAsteroidGenerator to "Stock" in Kopernicus_Config.cfg.  This will remove support for asteroid customization and only works well in stock-type systems (OPM and similar qualifiy).

Other settings for useKopernicusAsteroidGenerator is true (which is the default, customizable asteroids but no comets), and false, which allows an external mod (like CustomAsteroids) to take over the generation of comets/asteroids and just gets Kopernicus out of the way completely.

Currently there are no plans to change this approach, but I do recognize it is not perfect.  It will probably be revisited someday.

**Comment by Folkoer** [comment]
Was thinking about starting a new Beyond Home safe, so comets are not possible with that mod?
