### ISSUE TITLE
Kopernicus fails to load Vulture

### ISSUE THREAD

**Issue by Panzersmart** [Kopernicus/Kopernicus#510]
I want to use the Vulture system but it always says Kopernicus failed to load the custom planatary system. Can somebody help me

[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/7935530/Kopernicus.log)
[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/7935531/Kopernicus.Runtime.log)
[KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/7935535/KSP.log.txt)
?

**Comment by R-T-B** [comment]
Thanks for providing logs.  I will look into this and be right back with what I find.  I would suspect a missing dependency but we'll see.

**Comment by R-T-B** [comment]
Ok, so it looks like it could be either JanitorsCloset plugin acting up, or a bad install.  There are quite a few errors Kopernicus is reacting too (none of them caused by Kopernicus).  I would start by removing JanitorsCloset and see if that helps.  If there's an updated version, you can try that as well.

**Comment by Panzersmart** [comment]
So I removed it but this didnt fix it. Then I tried without any mods but this didnt work either. I think I installed Kopernicus wrong. Can you tell me how to install it properly?

**Comment by R-T-B** [comment]
Can I get a screenshot of your gamedata and then your Kopernicus subfolder of gamedata?  From there I can advise you what to do.

**Comment by Panzersmart** [comment]
Here are the Screenshots
![Screenshot (128)](https://user-images.githubusercontent.com/98414253/151374476-2ef24ad8-2097-4d25-aec0-2f2c9f136142.png)
![Screenshot (127)](https://user-images.githubusercontent.com/98414253/151374479-0c9f42c5-76f6-4ba5-90e3-de5eb3ab1658.png)
![Screenshot (126)](https://user-images.githubusercontent.com/98414253/151374481-5f273c05-606b-4883-99cb-d312a172878d.png)

**Comment by Panzersmart** [comment]
Here are the Screenshots
![Screenshot (131)](https://user-images.githubusercontent.com/98414253/151378016-a3e42cb9-e07b-4190-8ff4-aa7e122ecbc7.png)
![Screenshot (130)](https://user-images.githubusercontent.com/98414253/151378018-7692632a-6562-441c-a9ae-24a2c01268ad.png)
![Screenshot (129)](https://user-images.githubusercontent.com/98414253/151378022-a3823e39-2be0-45d2-9272-d8bd1808a433.png)

**Comment by R-T-B** [comment]
yeah, the issue is how you are extracting Kopernicus.  It's in your install dir /GameData/Kopernicus-1.12.1-71/GameData/Kopernicus.

It should simply be GameData/Kopernicus, without all those folders in between.

The easiest way to fix this would probably be to delete a the "Kopernicus-1.12.1-71" mess and manually drag just "Kopernicus" from the zip into your game data directory, since whatever archiver you are using seems to make extra folders.  Hopefully that would avoid the same issue.

Let me know if that helps.

**Comment by Panzersmart** [comment]
Thank you for your help. It finally worked. Thank you very much

**Comment by R-T-B** [comment]
No problem!  Enjoy!
