### ISSUE TITLE
koperkurnicus was not able to load custom planetary system.

### ISSUE THREAD

**Issue by marsrat** [Kopernicus/Kopernicus#520]
i have been getting an error stated above and i dont know what to do or what files to send to fix it?

**Comment by R-T-B** [comment]
Sorry I missed this.  You'll find the needed files in a "Logs" Directory in your ksp install in zip form, named something like "Kopernicus-Logs.zip"

I assume due to the age of this issue you probably moved on, but if you still have questions and/or want to submit those logs for help, make a new issue and I will try to help (with a little more speed this time ;) ).
