### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by ItsNava** [Kopernicus/Kopernicus#549]
Idk why this happens felt like ive tried everthing.

https://user-images.githubusercontent.com/116454321/197352849-4bea25d9-24f1-4bba-b464-2fe8fb80a042.png
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/9844889/KSP.log)
[ModuleManager.log](https://github.com/Kopernicus/Kopernicus/files/9844890/ModuleManager.log)

**Comment by raitarM** [comment]
same issue, have tried to get it running over the last couple of weeks. i have tried different solutions i found online going back almost five years but they were solved mostly due to the issues being botched manual installs or incompatibility with other mods. i'm using ckan and have fresh reinstalled the game and mods more than 10 times now. real solar system and realism overhaul, at least according to ckan, should be compatible

**Comment by rightarM92** [comment]
omg. words cannot convey the feelings. thank you and everyone involved. #554 has the solution for me. first parallax 1.31 and then real solar system and realism overhaul and it works
