### ISSUE TITLE
can't load custom planetary system due to exception in loading

### ISSUE THREAD

**Issue by EnderTrekkie** [Kopernicus/Kopernicus#562]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10462974/KSP.log)
[ModuleManager - Copy.ConfigCache.txt](https://github.com/Kopernicus/Kopernicus/files/10462984/ModuleManager.-.Copy.ConfigCache.txt)
uploaded as .txt because it wouldn't upload a .configcache (just rename it to not have the .txt at the end and it will be as it was)
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/10462989/Logs-Kopernicus.zip)
![image](https://user-images.githubusercontent.com/63455321/213612297-9340f23a-2321-4a5e-a3d7-c359f5220c1e.png)

As far as I know the only mod installed is Kopernicus.

**Comment by R-T-B** [comment]
the problem is you have nested gamedata folders, you should only have one and all the mod folders go beneath it.

Part of the log that indicates this follows:

`Folders and files in GameData:
GameData
Stock folder: Squad`

Thank you for your patience (we don't have the team we used to) and good luck.

**Comment by R-T-B** [comment]
Closing as part of a broader cleanup due to inactivity.  Reopen if you still have this issue or need more support.
