### ISSUE TITLE
Performance: Utility.GetMod should probably cache its results

### ISSUE THREAD

**Issue by JonnyOThan** [Kopernicus/Kopernicus#644]
I was looking through someone's profile capture and their FlightIntegrator, FlightInput, and Camera updates were very expensive.  A deep profile capture shows that it's dominated by Utility.GetMod, invoked by VertexHeightOblate:

![image](https://github.com/user-attachments/assets/913d637e-e5ed-41b0-bf5b-df79f905c448)

https://github.com/jamespglaze/VertexHeightOblateAdvanced/blob/7263707846db6415349d5f7eeecf5a6d3d4055d2/VertexHeightOblateAdvanced/CameraHijacker.cs#L55

I don't know what else might have this problem but it seems like maybe Kopernicus should just cache the results for each body assuming they never change.

https://github.com/jamespglaze/VertexHeightOblateAdvanced/issues/3

**Comment by JonnyOThan** [comment]
per gotmachine, a linear search over the private sphere.mods field would likely be better than caching (it's simpler at least):

```
public static T GetMod<T>(PQS sphere) where T : PQSMod
{
    for (int i = sphere.mods.Length; i-- > 0;)
        if (sphere.mods[i] is T mod)
            return mod;
    return null;
}
```

**Comment by gotmachine** [comment]
Caching would involve a double lookup on a static `Dictionary<PQS, Dictionary<Type, PQSMod>>`. Typically, a body only has a handful of PQSMods, so the performance gain would likely not be realized in many cases, especially since a lookup on `PQS` will be slow as it derive from `UnityEngine.Object`.
But the main issue is that a body PQS controller and its PQSMods have non-trivial lifetime rules, so this would require a lot of additional logic and hooks to correctly invalidate that cache.
