### ISSUE TITLE
PQSMod Loaders that are outside of Kopernicus.dll fail to parse certain properties

### ISSUE THREAD

**Issue by HappyFaceIndustries** [Kopernicus/Kopernicus#91]
I've been encountering issues with my custom PQSMods: Whenever the parser loads them, any non-struct type loaders (strings, ParserTargetCollections, Texture2DLoaders, etc.) load properly, but fail to set the values in the PQSMod, so they throw NullRefs whenever they are referenced by the PQSMod. They are not null if referenced in the loader.

I investigated a little bit more, and found this strange thing:

![screenshot140](https://cloud.githubusercontent.com/assets/7258677/10422564/af27d23c-7081-11e5-954e-b1ec03142866.png)

After calling UnityEngine.Resources.FindAllObjectsOfType<T>(), I found that, for whatever reason, **TWO** PQSMods were being added, which seemingly had the same parent, despite the Body.Log and GetComponentsInChildren<T>() only showing one.

I then looked through the components and other properties of those two objects, and found that 1 of them DID have the correct properties passed by the Loader, and the other didn't, although they both still had the struct properties from the loader correct. The one with the correct properties also happened to be the one unnoticed by GetComponentsInChildren<T>().

The code I used to come to these conclusions is in the ModularNoise and PQSMod_ ModularNoise classes in the ModularNoise.cs file, in the development branch of KopernicusExpansion. It includes the debug code. 
[Link to debug code](https://github.com/HappyFaceIndustries/KopernicusExpansion/blob/de52047832f640c2c9f5ea1bee751c833b90df3f/KopernicusExpansion/Configuration/ModularNoise.cs#L92)

I loaded the same code into a Kopernius fork, and it doesn't seem to happen to stuff inside Kopernicus.dll

**EDIT : Apparently, this issue only affects properties whose loaders are outside Kopernicus.dll. Texture2DLoaders and other non-struct loaders from Kopernicus.dll work fine, but my own NoiseLoader class doesn't.**

**EDIT 2 :  It appears that structs have nothing to do with this, it's just external Parsers in external PQSMods that have the issue.**

**Comment by HappyFaceIndustries** [comment]
So I just loaded up my fork of Kopernicus, and tried almost completely rewriting the ModLoader system, and nothing got fixed. I still don't know what's going on here, everything is a shot in the dark...

**Comment by HappyFaceIndustries** [comment]
Apparently the Kopernicus Loader might not be at fault here.

I tried loading the PQSMod from an ExternalParserTarget, and it still had the same issue.

**Comment by HappyFaceIndustries** [comment]
I have no clue what's going on, but I can call this code in my PQSMod's OnSetup to fix it:

    var other = UnityEngine.Resources.FindObjectsOfTypeAll<PQSMod_ModularNoise> () [1];
    this.noise = other.noise;
    this.Operators = other.Operators;

It just grabs the second PQSMod that actually has the correct values set, and takes it's values, although it doesn't work with multiples of the same PQSMod yet, even on different planets.

**Comment by ThomasKerman** [comment]
I think that I have an idea what's going on here. Unitys Serialization System (i.e. persistence between scenes) can only serialize basic types (string, bool, int, long, short etc.) and types flagged with the [Serializable] Attribute. Because they are recognized when Unity starts, you can only put serializable types into Assembly-CSharp(-firstpass).dll. When an object is not serializable, it'll get lost when the object is instantiated. The only solution I know is to use a DontDestroyOnLoad-ed MonoBehaviour to store your stuff.

Oh and Resources.FindObjectsOfTypeAll returns two instances of the mod, because there's one mod in the running system and one in the systemPrefab. What you are doing is restoring the lost values using the valid values from the prefab at runtime, so basically "manual serialization".

Unity is silly sometimes.....

**Comment by HappyFaceIndustries** [comment]
OK, that explains it... Should I just run DontDestroyOnLoad on my PQSMods?

Anyways, the changes I made to the PQS system did make everything much cleaner, so I might tidy that up and submit it as a pull request.

Thanks!

**Comment by ThomasKerman** [comment]
That won't help, because the objects you are loosing don't derive from MonoBehaviour, so they aren't serialized, when the PSystemManger instantiates the prefab into the live planetary system.

As for the changes to ModLoader: I'm planning to rewrite big parts of the Kopernicus Loading stack for 0.5, to make use of a more opened and modular API (=> API branch). I'll rewrite the mod loading code, when I redo the parsing library. Feel free to submit pull requests though, maybe I'll release some bugfixes as 0.4.1
